# try to get rustfmt to do something sane.
# apparently that's hard!

# max_width = 80
# lines should be kept around 80 chars even thought rustfmt has a nightmare
# about that

reorder_imports = true
reorder_imported_names = true

single_line_if_else_max_width = 80 # this isn't nearly permissive enough
take_source_hints = true
match_block_trailing_comma = true

fn_return_indent = "WithWhereClause"
fn_brace_style = "AlwaysNextLine"
# fn_args_layout = "Block"

closure_block_indent_threshold = 2

# what do these things mean
# fn_call_style = "Visual"
# fn_call_width = 80

# I don't really like this
# call_function(x,
#               y,
#               z);
#
# would prefer
# call_function(
#   x, y, z
# );
#
# or something. maybe someday

# other wishes:
# - allow structs to have vertically indented members

# or occasionally!
# x =
#  Some(long thing in here help)
