[package]
name = "uitest"
version = "0.1.0"
authors = ["David Zmick <dpzmick@gmail.com>"]

[dependencies]

[dependencies.conrod]
git = "https://github.com/PistonDevelopers/conrod.git"
features = ["glium", "winit"]
